### ISSUE TITLE
运行项目Chapter10-RNInteractionWithNative  ----RNAddNative  报错，JSON解析异常？

### ISSUE THREAD

**Issue by mnb65482** [mrarronz/react-native-blog-examples#7]
03-05 10:40:55.181 870-870/com.rnaddnative E/unknown:ReactNative: Unable to display loading message because react activity isn't available
03-05 10:40:55.354 870-931/com.rnaddnative E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.rnaddnative, PID: 870
    java.lang.IllegalStateException: Expected BEGIN_ARRAY but was STRING
        at android.util.JsonReader.expect(JsonReader.java:310)
        at android.util.JsonReader.beginArray(JsonReader.java:277)
        at com.facebook.react.devsupport.BundleDeltaClient.patchDelta(BundleDeltaClient.java:98)
        at com.facebook.react.devsupport.BundleDeltaClient.storeDeltaInFile(BundleDeltaClient.java:52)
        at com.facebook.react.devsupport.BundleDownloader.processBundleResult(BundleDownloader.java:281)
        at com.facebook.react.devsupport.BundleDownloader.access$200(BundleDownloader.java:35)
        at com.facebook.react.devsupport.BundleDownloader$1.onResponse(BundleDownloader.java:153)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

**Comment by mrarronz** [comment]
抱歉这么久才回复，我在真机下运行没有出现这个问题。用的华为荣耀V10，由于之前为了清理磁盘空间把所有项目的node_modules文件夹都删掉了，所以重新安装了一遍，运行出来没有发现上述问题。你这个错误应该是bundle加载失败导致的，“Unable to display loading message”是加载进度的信息都显示不了，清理掉node_modules再重新安装试试。
1. rm -rf node_modules
2. yarn install 或者 npm install
3. react-native run-ios 或者 react-native run-android

**Comment by mnb65482** [comment]
感谢您抽空处理我的问题。确实是您说的这个情况。还有就是我重新在进程中kill掉node.js进程，再重新运行也解决这个问题了。再次感谢。
